-- MySQL Script generated by MySQL Workbench
-- Tue Feb 14 16:27:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mps` DEFAULT CHARACTER SET utf8 ;
USE `mps` ;

-- -----------------------------------------------------
-- Table `mps`.`agenda_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mps`.`agenda_usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(100) NOT NULL,
  `usuario_email` VARCHAR(100) NOT NULL,
  `usuario_status` INT NOT NULL,
  `usuario_senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mps`.`agenda_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mps`.`agenda_eventos` (
  `evento_id` INT NOT NULL AUTO_INCREMENT,
  `evento_titulo` VARCHAR(100) NOT NULL,
  `evento_data_hora` DATETIME NOT NULL,
  `evento_descricao` VARCHAR(200) NOT NULL,
  `evento_status` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`evento_id`),
  INDEX `fk_agenda_eventos_agenda_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_evento`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mps`.`agenda_usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
